import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Archivo_Black, Lexend_Mega, Space_Grotesk } from "next/font/google";

const lexend_mega = Lexend_Mega({
  subsets: ["latin"],
  variable: "--font-head",
  display: "swap",
});

const space = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", lexend_mega.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
